name: Mighty LA
favicon: null
layout_spectrum: 0.3850746031384915
typography_spectrum: 0.5466270451433957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4142306330613792
  lightness: 0.3835337641648948
  saturation: 0.3530289651826024
  rhythmicContrast: 0.975594469346106
purpose: []
