name: Mighty LA
favicon: null
layout_spectrum: 0.21194
typography_spectrum: 0.38671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1eef4'
    - '#1c1c1e'
    - '#4c4c4a'
    - '#a09694'
    - '#7e1f2f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
