name: Mighty LA
favicon: null
layout_spectrum: 0.50096
typography_spectrum: 0.38671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3c4154'
    - '#127e9f'
    - '#e5dfd0'
    - '#7b7074'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
