name: Mighty LA
favicon: null
layout_spectrum: 0.3850746031384915
typography_spectrum: 0.5466270451433957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#061622'
    - '#57859a'
    - '#1c3943'
    - '#8baaa9'
    - '#dce7ec'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.3530289651826024
  rhythmicContrast: 0.975594469346106
purpose: []
